#!/bin/bash

APPS="$HOME/.local/share/applications"
BINS="$HOME/.local/bin"
SCHEMEMIME="x-scheme-handler/edit-source"

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "[Desktop Entry]
Name=Edit Source Protocol Handler
GenericName=Edit Source Protocol Handler
Comment=Enables links to edit files from the browser
Icon=document-edit
TryExec=$BINS/edit-source-url
Exec=$BINS/edit-source-url %u
Terminal=false
Type=Application
Categories=Accessories
MimeType=x-scheme-handler/edit-source
NoDisplay=true" > "$APPS/edit-source-url.desktop"
cp "./edit-source-url" "$BINS/."

if [ ! -e "$APPS/mimeapps.list" ]; then
  echo "[Added Associations]" > "$APPS/mimeapps.list"
fi

if grep "$SCHEMEMIME" "$APPS/mimeapps.list" &>/dev/null; then
  echo "edit-source schema already registered - skipping"
else
  echo "x-scheme-handler/edit-source=edit-source.desktop"
  LINE=`grep -n "\[Added Associations\]" "$APPS/mimeapps.list" | cut -d: -f1`
  let LINE=$LINE+1
  if [ ! $LINE == '' ]; then
    sed "$LINE i${SCHEMEMIME}=edit-source-url.desktop" "$APPS/mimeapps.list" > "$APPS/mimeapps.list.new"
  else
    echo -e "[Added Associations]\n${SCHEMEMIME}=edit-source-url.desktop" >> "$APPS/mimeapps.list.new"
  fi
  mv "$APPS/mimeapps.list.new" "$APPS/mimeapps.list"
fi
